# Generated by Django 3.2.13 on 2022-09-16 15:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='dummies')),
                ('title', models.CharField(max_length=50)),
                ('text', ckeditor.fields.RichTextField(max_length=50000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
